; input_map.ini

[Keyboard]
; Movement
Move_Up = W
Move_Left = A
Move_Down = S
Move_Right = D

; Action
Interact = E

; UI
UI_Up = W
UI_Down = S

; Menu
Menu = Escape
Menu_Up = W
Menu_Left = A
Menu_Down = S
Menu_Right = D
Menu_Select = E
Menu_Cancle = C